---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config-map
data:
  CART_HOST: "cart:80"
  USER_HOST: "user"
  AMQP_HOST: rabbitmq"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    name: payment
    tier: app
spec:
  containers:
  - name: payment
    imagePullPolicy: Always
    image: richeb/payment:k8
    envFrom:
    - configMapRef:
        name: payment-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    name: payment
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    