---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config-map
data:
  CATALOGUE_HOST: "http://catalogue"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    name: cart
    tier: app
spec:
  containers:
  - name: cart
    imagePullPolicy: Always
    image: richeb/cart:v1
    envFrom:
    - configMapRef:
        name: cart-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    name: cart
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    