---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config-map
data:
  CART_ENDPOINT: "cart"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    name: shipping
    tier: app
spec:
  containers:
  - name: shipping
    imagePullPolicy: Always
    image: richeb/shipping:k8
    envFrom:
    - configMapRef:
        name: shipping-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    name: shipping
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    