---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSSWORD: cm9vdDEyMwo=
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql-db
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: richeb/mysql:v1
    envFrom:
    - configMapRef:
        name: mysql-config-map
    - secretRef:
        name: mysql-secret
    ports:
     - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
   name: mysql-db
   tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306

