---
apiVersion: v1
kind: configMap
metadata:
  name: mysql-config-map
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: c2hpcHBpbmc=
  password: c2VjcmV0
---
apiVersion: v1
kind: pod
metadata:
  name: mysql
  labels:
    name: mysql-db
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: always
    image: richeb/mysql:v1
    envFrom:
    - configMapRef:
      name: mysql-config-map
    - secretKeyRef:
      name: mysql-secret
    ports:
     - containerPort: 3306
---
apiVersion: v1
kind: service
metadata:
  name: mysql-service
spec:
  selector:
   name: mysql-db
   tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306

