---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config-map
data:
  MONGO_URL: "mongodb://mongodb-service:80/catalogue"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - name: catalogue
    imagePullPolicy: Always
    image: richeb/catalogue:k8-1
    envFrom:
    - configMapRef:
      name: catalogue-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    