---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
data:
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb-service:80/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: api
spec:
  containers:
  - name: user
    image: richeb/user:v1
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: user-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
   name: user
   tier: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080