---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 500m
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
  -name: web
  imagePullPolicy: always
  image: richeb/web:k8
  ports:
    -containerPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: frontend
  ports:
    -protocol: TCP
    port: 80            # Load Balancer port
    targetport: 80      # Container port we mentioned above

    